### ISSUE TITLE
StompMessage->compile()

### ISSUE THREAD

**Issue by Aslan125** [forresthopkinsa/StompProtocolAndroid#2]
please pay attention

https://github.com/NaikSoftware/StompProtocolAndroid/issues/77

**Comment by forresthopkinsa** [comment]
Yes, I saw your update on that issue; it hasn't even been 20 minutes since you posted it. If you want me to _remove_ the double-newline, then **that** is something that would be relevant to this repo; otherwise, this issue isn't very useful here...

In other words, either rephrase this issue to be more relevant, or close it.

**Comment by forresthopkinsa** [comment]
Okay well I fixed your problem anyway, check out the [latest release](https://github.com/forresthopkinsa/StompProtocolAndroid/releases/tag/17.09.1). 😄 🎉

**Comment by forresthopkinsa** [comment]
@Aslan125 Can I get confirmation that your problem is solved? I don't know what your specific configuration is, so I can't really test it myself. If it's not solved, then this needs more discussion.

**Comment by forresthopkinsa** [comment]
Closing due to no response
